---
title: "Exploratory"
author: "Nivretta Thatra"
date: "March 15, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Installed the necessary dependencies by: 

```{r, load libraries, message=FALSE}
#source("https://bioconductor.org/biocLite.R")
#biocLite("wateRmelon")
#biocLite('limma')
#biocLite('minfi')
library(wateRmelon)
library(minfi)
library(dplyr)
library(tidyverse)
library(readr)
```

##Load data

Tried to load preprocessed data in attempt to work from it directly rather than having to regenerate it from preprocessing script...didn't work.
```{r, read data}

setwd("../processed_data/")

#data import is not working correctly, read_delim is the only function that gets close
#read.delim, read.csv don't work
#read_delim problem: row names are assigned to as first sample values, final sample not imported
#data <- read_delim("data.txt"," ", escape_double = FALSE, trim_ws = TRUE)

design <- read.csv("des.txt", sep="\t", header=TRUE)

#trying to get metadata and data into one dataframe to do exploratory visualizations, not possible because data is too big

#colnames(data) <- c(as.character(design$Samplename))

#full <- cbind(design, t(data))


```

##Plotting

Ideally we'd plot methylation at a random CpG sight and see how it varies with covariates. Below is sample code for how we'd that, if data loading was working.

```{r, eval=FALSE}
#Sample code

#random cpg site
probe_row <- 2000

#get the site name 
probe_name <- colnames(full)[probe_row]

ggplot(full, aes(x = as.factor(time_num), y = full[probe_row])) + 
  geom_boxplot(aes(fill=Ethnicity), show.legend = TRUE) + 
  geom_jitter(width = 0.3) + 
  facet_wrap(~Sample_Group) + 
  xlab("Gestational Age") + 
  ylab("Beta values") +
  ggtitle(paste("Beta values for CpG site", probe_name)) +
  stat_summary(fun.y = mean, geom="point", colour="darkred", size= 3)

```


